################ AUTH ################

### POST 
POST http://localhost:3333/v1/auth/register
Content-Type: application/json

{
    "name": "William",
    "username": "william123",
    "email": "william123@gmail.com",
    "password": "William123",
    "age": 18
}

### POST
POST http://localhost:3333/v1/auth/login
Content-Type: application/json

{
    "email": "william123@gmail.com",
    "password": "William123"

}